Prevent invalid arg on call

diff --git a/awesome-release b/awesome-release
--- a/awesome-release
+++ b/awesome-release
@@ -32,7 +32,8 @@ while true ; do
     ;;
     (--) shift; break;;
     (-*) echo "$0: error - unrecognized option $1" 1>&2; print_help 1;;
-    (*) break;;
+    ("") break;;
+    (*) echo "$0: error - unrecognized option $1" 1>&2; print_help 1;;
     esac
     shift
 done
